### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [chrislongo/Pig#10]
I would like to use your grammar for PigLatin but I don't know what licensing terms you're distributing it under. Any chance you could pick one from here: http://choosealicense.com?

**Comment by pchaigno** [comment]
@chrislongo Did you get a chance to look into this? I'm considering using your grammar at [github/linguist](https://github.com/github/linguist) to highlight PigLatin code on GitHub.

**Comment by chrislongo** [comment]
Go for it. It's MIT License.

**Comment by pchaigno** [comment]
Great! Could you add that information in a `LICENSE` file in the repository or directly in the `README`?

**Comment by chrislongo** [comment]
Done.

**Comment by pchaigno** [comment]
Thanks! :zap:
